### ISSUE TITLE
Settings not changed in Nested Partials 

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#678] opened 2017-03-30 16:22 UTC
Settings changes in a partial are not reflected when that partial is used inside another partial (nested partials)

[PartialTest.rw.zip](https://github.com/yourhead/s3/files/883080/PartialTest.rw.zip)

1. Open project
2. On Home page, double click the header partial to edit.
3. On the 1 Column stack, add 20px margin via the slider setting.
4. Click Back.
5. Go to Nested Partial page
6. Double Click the Nest Partial
7. Double Click the Header Partial
8. Notice that the 1 column stack does not have a 20px margin

**Comment by joeworkman** [comment] 2017-03-30 19:03
As a test, I built this exact project in RW 7.0.4 and the exact behavior exists. However, I assume that this is because Stacks now stores this data differently since and update post-RW 7.1

**Comment by yourhead** [comment] 2017-06-23 18:48
i have tested and i can no longer duplicate this bug.

i do think this is still possible if you start with a project file that was created pre-RW7.1.

but that means this bug should be isolated only to old data -- only when it contains nested partials -- only when the deeper partial is edited -- only when the same partial exists on unloaded pages. and even then it's only a cosmetic bug.  once the file is reopened it should be correct.

so...  i'm letting this one lie.

if a similar bug is still/again found -- please post as a new bug with a detailed list of steps.  the current list of steps is sufficiently detailed -- but starts with an unspecified file -- depending on the state/source of the file -- the behavior changes. a good set of steps would avoid/resolve that ambiguity by starting with a known file or starting with a new file -- saving -- and then opening.

**Comment by joeworkman** [comment] 2017-07-07 13:55
If I follow the steps above, this bug still happens for me.

**Comment by joeworkman** [comment] 2017-07-07 13:58
I can still replicate this with a completely new project file as well.

**Comment by yourhead** [comment] 2017-07-08 07:47
ok, i've done some work and i have come across two separate partial related bugs. one in particular seems to fit your file it requires

- a nested partial on at least one page
- the same partial used on another page non-nested
- the non-nested one has to load first -- either by user interaction or luck of which page RW displays first

with this set of circumstances the partial instances on these two pages will be related -- but not really linked up. this can result in a whole bunch of odd behavior:  changes may not be shared, pages may not be marked as needing publishing, new instances of the partial may not display correctly... and probably more.

since these two instances are not really sharing info -- if they are both edited independently -- which content "wins" the save can vary.

All of this stuff is caused by the non-linked instances. I've fixed that and will release tomorrow.

**Closed as completed** 2017-07-08 19:54 UTC
Labels: bug
