### ISSUE TITLE
HTML template with "page" scope no loner works for backward compatibility.

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#178] opened 2015-06-15 09:11 UTC
My stacks with HTML templates with "page" scope no loner work in S3.

The template is not present in the head when previewing the page.
Nor is it present in edit mode.

My template in this case is simply a link to font awesome.

```
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
```

My plist looks like this : 

![info_plist](https://cloud.githubusercontent.com/assets/1026876/8156727/d97d37b8-1346-11e5-8db7-f4e999761e6f.png)

**Comment by doobox** [comment] 2015-06-15 09:32
Bug #179 is likely related to this.

**Comment by yourhead** [comment] 2015-06-15 16:46
Nearly all of the built in stacks use the page scope. As does this image fun stacks. They appear to work as expected.

I do not doubt that you are seeing an error. However it is likely something that you are doing that is different than other stacks. I need that info.

**Comment by yourhead** [comment] 2015-06-18 01:38
suspect this is a duplicate of #195

**Closed as completed** 2015-06-18 01:38 UTC
Labels: bug, duplicate, doesn't repeat
