### ISSUE TITLE
background section of info pane does not display correctly

### ISSUE THREAD

**Issue by girlcarew** [yourhead/s3#395] opened 2015-08-01 13:16 UTC
Open RW.
Open a Stacks doc.
Open the background section of the Info Pane (if it's not already).
Click the "Color" button (next to "Type"), then click the "Image" button.

The color well appears after I click Color, but when I click Image the section expands as if it's going to show me more stuff, but all I see is the top edge of something and then blank space.

**Comment by yourhead** [comment] 2015-08-01 15:33
duplicate of #394

**Closed as completed by yourhead** 2015-08-01 15:33 UTC
