### ISSUE TITLE
S3 Fails loading S2 Saved instances of Formsnap stack.

### ISSUE THREAD

**Issue by yabdab** [yourhead/s3#487] opened 2015-08-31 18:19 UTC
Here is your official issue .

**Comment by yabdab** [comment] 2015-09-17 13:59
Formsnap pages that were created using Stacks 2 previously, fail to display properly when opened in Stacks 3. The only current work around is as follows...
1. Open your FormSnap page and Select the Base stack.
2. Preview the page.
3. Check, then uncheck hide checklist ( or interact with any HUD settings )
4. Make sure collapse in edit mode is NOT checked.

**Comment by yabdab** [comment] 2015-09-17 13:59
Bug does repeat every time affected project is opened.

**Comment by joeworkman** [comment] 2015-09-17 16:29
This is interesting because I am having issues with Foundation form fields getting displayed sometimes in Edit Mode.

**Comment by joeworkman** [comment] 2015-09-17 16:44
Here is a project file that displays the issue for me. This is from the customer and I have not been able to repeat this behavior with a new project file. 

Project File: https://infinit.io/_/K8MFSrL

### Steps
1. Open the above project file. 
2. Notice there are not any sub stacks inside the Form Base. The %slice% appear to not be displayed at all. 
3. You can change settings inside Form Base or add new stacks to the page. The Form Base content remains hidden. 
4. Preview the page and see how much really is supposed to be there. 
5. Go back to edit mode. 
6. Add a new stack to the page or toggle a setting in Form Base. Magically, everything comes back. 

### Edit Mode

![screen shot 2015-09-17 at 9 32 57 am](https://cloud.githubusercontent.com/assets/225628/9939520/88365786-5d1f-11e5-8fdf-ad0d895c70e8.png)

### Preview

![screen shot 2015-09-17 at 9 33 02 am](https://cloud.githubusercontent.com/assets/225628/9939538/a4e14418-5d1f-11e5-8af7-2f3ab301361b.png)

**Comment by joeworkman** [comment] 2015-12-04 21:06
This is still labeled `doesn't repeat`. Does my example repeat? I am still getting users asking me when this will get fixed.

**Comment by yourhead** [comment] 2015-12-04 21:19
the challenge here isn't in seeing the corrupted file. the challenge here is in understanding how it got that way.

also:  you've sent a file that is very complex. this, of course, makes it very difficult to isolate the problem from all of the other stuff going on. when things are isolated i can solve them easily. when they're not i tend to put them off until i understand them better. if you can help make the problem very simple then i can solve it today.

**Comment by yourhead** [comment] 2015-12-12 19:29
spent about 6 hours cutting the example down to a useful size. would have been so amazing if someone could have helped with that.  :-P

but...   shhhhhh...   finally done and the problem is quite obvious.

[simple.rw6.zip](https://github.com/yourhead/s3/files/60231/simple.rw6.zip)

**Comment by yourhead** [comment] 2015-12-12 20:09
the problem is that the file has a lot more content than the stack currently displays. in the saved file the FormSnap Base has a lot of children:

```
HTML Content :: stackID:%html% :: instanceID:283,
HTML Content :: stackID:%html% :: instanceID:284,
HTML Content :: stackID:%html% :: instanceID:285,
HTML Content :: stackID:%html% :: instanceID:286,
HTML Content :: stackID:%html% :: instanceID:287,
HTML Content :: stackID:%html% :: instanceID:288,
HTML Content :: stackID:%html% :: instanceID:289,
HTML Content :: stackID:%html% :: instanceID:290,
Text Content :: stackID:%text% :: instanceID:291,
Text Content :: stackID:%text% :: instanceID:292,
Container Node :: stackID:%slice% :: instanceID:293,
HTML Content :: stackID:%html% :: instanceID:311,
HTML Content :: stackID:%html% :: instanceID:312,
Text Content :: stackID:%text% :: instanceID:1552
```

and yet the template has only one place to put these things:  a single %slice%
IOW: lots of data and nowhere to put it.

how did it get this way?   i don't know, but if i had to guess i'd say that this stack used to have a template with a different structure and it was changed -- perhaps more than once. maybe there was a repeat and now there isn't? i'm not 100% sure.

this is not a normal situation and stacks is trying to do the best it can to do the best to make lemonade from these lemons.  **obviously if this lemonade is not something you want then just don't give Stacks lemons.** :-P

the reason that the edit mode display changes is because the pattern of the content in this particular file is interpreted as the content of a  `%repeat%`  that is currently not being displayed -- so it shows very little.  this particular behavior is not a bug, but just a comment of how the repeat template works.

i'm tempted to just say: this isn't a bug. it's a feature. stacks is doing what it always has and i think that's the right thing. it's the most robust way to handle repeat templates.  the fact that you've managed to confuse the shit out of stacks is not a bug.  garbage in, garbage out, end of story.

…but…

repeat is being deprecated soon. and used less. perhaps we can sacrifice a bit of repeat robustness and detect this situation specifically and resurrect these files from the dead.  no promises.

**Comment by yourhead** [comment] 2015-12-12 20:10
closing: not a bug.
opening an api feature request #524 with specific details on what is required for this change.

**Closed as completed by yourhead** 2015-12-12 20:10 UTC
Labels: bug, completed
