### ISSUE TITLE
slice container with addTypes / allowedTypes still allows dragging images to it

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#552] opened 2016-02-12 06:44 UTC
I have a slice container with 2 defined sub stacks:

`%slice -addTypes="StackA,StackB" -allowedTypes="StackA,StackB"%`

I am able to drag either StackA or StackB into this container only, which works a designed.
But when dragging an image from my Finder directly into this container, a new Image Stack with this image is created in that container.

Stacks version 3.0.5b5

**Comment by joeworkman** [comment] 2016-02-12 07:05
You know that you are supposed to use the bundleID, not the stack name....

**Comment by jrondorf** [comment] 2016-02-12 07:11
I know that. This is just an example text. Then take 

`%slice -addTypes="com.workmann.stacka,com.workmann.stackb" -allowedTypes="com.workmann.stacka,com.workmann.stackb"%`

**Comment by jrondorf** [comment] 2016-02-12 07:15
Or ImageFunStack `com.yourhead.stacks.list`

This has `%slice -addTypes="com.yourhead.stacks.listItem,text" -allowedTypes="com.yourhead.stacks.listItem,text"%` as addTypes / allowedTypes, but still you are able to drag an image to that.

In order to achieve that, it should be:
 `%slice -addTypes="com.yourhead.stacks.listItem,text,image" -allowedTypes="com.yourhead.stacks.listItem,text,image"%`

**Comment by yourhead** [comment] 2016-02-17 00:53
duplicate of #174

**Closed as completed** 2016-02-17 00:53 UTC
