### ISSUE TITLE
Using multi monitors with stacks 3

### ISSUE THREAD

**Issue by MACMAD** [yourhead/s3#462] opened 2015-08-19 13:22 UTC
I have 2 monitors in my workflow and I was really looking forward to options of making the Library and info panes as separate windows that I could place on my second monitor while I worked on my main monitor. They work as they should up to a point. 
If I keep them on the same monitor they will keep their position if I open and close them. This does not hold true on multiple monitors. They will revert back to the screen that the main window is opened.
I also noticed that if I opened two projects at the same time and created windows for both the library and info is that they react differently. Although there may be 4 panes open, the 2 libraries windows apply to both projects. The info windows operate exclusive to each project. The problem is identifying which info window applies to which project. The simple solution is to apply the project name to the top of the window.
It really becomes a mess of windows when I decide to close close a project and them open it again. The windows are still on my second monitor and new ones are created on my main monitor. So just so you can wrap your head (get it) around this one, I now have 4 floating windows on my second window from the same project. Every time I close a project, the number goes up by two if I move the two new ones to the second screen. I stopped at 2, 4 info and 4 Library. 
The mess does not stop there. Should I switch to another app and return to RW6 all of the floating windows jump back to my main screen. They stay on the screen even if I close the open project. The only thing that closes out the floating windows is by quitting the app. I have attaches to screen shots for you to see. I am running OS X 10.10.5 on a iMac (27-inch, Mid 2010) 2.93 GHz Intel Core i7 20 GB 1333 MHz DDR3

![project open](https://cloud.githubusercontent.com/assets/1932883/9357121/28a84622-4653-11e5-9000-7896ea2a0362.png)
![project closedd](https://cloud.githubusercontent.com/assets/1932883/9357160/57193c00-4653-11e5-9411-64b6e8de04d3.png)

**Comment by yourhead** [comment] 2015-08-20 16:08
thanks for the details. i think situation will be improved when #456 is resolved. if it is not, please let me know.
duplicate of #456

**Closed as completed by yourhead** 2015-08-20 16:08 UTC

**Comment by MACMAD** [comment] 2015-08-21 11:59
Re #462
-Floating panes (library & info) still not holding position on second monitor when opening up project. Revert back to application screen
- No identification of panes if multiple projects opened.
  
   -Library pane generic, applies to all projects opened. Still open one per project
   -Info pane unique to project, no way to identify which pane to which project
- Panes close now on closing project....thanx

**Comment by yourhead** [comment] 2015-08-21 16:31
@MACMAD - can you help me duplicate any of these bugs -- windows do seem to remember their location for me just fine
