### ISSUE TITLE
CSS Libraries are added twice in Edit Mode

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#494] opened 2015-09-06 19:51 UTC
If you add my Site Styles stack to the page, it adds a <link> tag for my foundation.css library twice. 

I just want to make sure that this does not have any performance indicators. The hrefs in each is slightly different.

**Comment by joeworkman** [comment] 2015-09-06 19:51
![screen shot 2015-09-06 at 12 49 27 pm](https://cloud.githubusercontent.com/assets/225628/9706296/06399856-5496-11e5-8039-fb020df96267.png)

**Comment by joeworkman** [comment] 2015-09-06 19:53
I should add that I discovered this when trying to debug another issue. It may be related. Whenever Site Styles is on the page and you delete any stack form the page, Edit Mode gets scrolled to the top. This drives me nuts and wondering if this could be the culprit.

**Comment by yourhead** [comment] 2015-09-14 16:37
i strongly suspect this is a duplicate of #500. i cannot duplicate this, mostly likely because #500 has already been fixed. if you still notice this after the next round of updates, please resubmit with more details on how to reproduce.

**Closed as completed by yourhead** 2015-09-14 16:37 UTC
