### ISSUE TITLE
Stacks no longer updates in Edit mode when Editing css files on .devstack

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#361] opened 2015-07-25 19:23 UTC
Stacks still updates the stack when editing the html file of .devstack but has stopped updating css files.

This is a new issue for me because it has always updated css files as well as html files. It has only been in the last two (the most recent two) updates that it has not worked properly.

**Comment by yourhead** [comment] 2015-07-25 22:59
i'm having trouble duplicating this.  can you be specific about how you are included this CSS from your plist.

**Comment by bbyrdhouse** [comment] 2015-07-26 00:29
As a template array like this:

```
<dict>
    <key>filename</key>
    <string>style.css</string>
    <key>type</key>
    <string>css</string>
</dict>
```

Its only done this over the last "developers" beta or two before that it would update within a couple of seconds of saving a change in my style.css file.

**Comment by yourhead** [comment] 2015-07-27 03:41
i can only seem to duplicate this on stacks that are installed within a linked directory -- do you think that could be it?

**Comment by bbyrdhouse** [comment] 2015-07-27 05:47
not sure ... what does that mean?

**Comment by yourhead** [comment] 2015-07-27 06:03
it means the general case of this bug is… well… nonexistent. i haven't been able to see it it myself.

so u spent a couple hours trying to come up with other twists to add to it that maybe you might be doing.

i have found that the automatic reload doesn't catch stacks that are symlinked. 

if this is what you're seeing i would like verification. otherwise i just have to close this as i'm not able to reproduce it without more specific info and i've already spent too many hours trying to guess what you might be seeing with no real results to show for it.

**Comment by bbyrdhouse** [comment] 2015-07-27 06:09
Forgive my ignorance but what is a 'stack that is symlinked' .... I only reported this as a bug because something that was working stopped working. 

What I am seeing is that when I am editing a .devstack's css file in Espresso and then save the file. The changes are not seen in Stacks. IF I make a change to the template.html file then I do see the change within a second or two. Editing the css requires a restart of RW for me to see the changes made to the css file.

As I mentioned earlier, this is a new problem for me. Previous to the last couple of updates changes to css files were seen immediately in Stacks (RW).

**Comment by atavernor** [comment] 2015-07-28 12:06
I am seeing the same, again just with CSS files. They are not symlinked files.

There is a simple test stack [here](https://infinit.io/_/DfVkiqt)

Change either of the colors in styles.css and it does not update in edit mode.

The image below shows the saved styles.css in sublime with a new h2 color of white - the webkit inspector still shows the original color of green as per the css when the stack was dropped on to the page.

![css](https://cloud.githubusercontent.com/assets/8500380/8933593/9b438ef4-353b-11e5-92ad-a9e4ea19b96c.jpg)

Then restart RapidWeaver (no changes to any files) and the new css is applied...

<img width="623" alt="screen shot 2015-07-28 at 13 09 22" src="https://cloud.githubusercontent.com/assets/8500380/8930907/fa85662e-3529-11e5-9885-a170bce80200.png">

**Comment by atavernor** [comment] 2015-07-28 12:41
Further info:  I have just reverted to v.3.0.0.x4 and it works perfectly.

**Comment by bbyrdhouse** [comment] 2015-07-28 14:16
Where do you get the older versions of S3 ... I need to revert to an earlier one as well

**Comment by yourhead** [comment] 2015-07-28 14:54
@atavernor -- thanks for the example and details. helped a lot. fixed in the next build.

**Closed as completed** 2015-07-28 22:54 UTC
Labels: bug, completed
