### ISSUE TITLE
Library starts closed at launch (should not)

### ISSUE THREAD

**Issue by leifottosson** [yourhead/s3#350] opened 2015-07-22 15:54 UTC
Launch RW.
Choose "New project".
Add stacks page.
Library starts closed even that it's not checked in the prefs that it should.

Checking/unchecking the box in the prefs and restarting RW doesn't help.
It has been working as it should earlier.

**Comment by yourhead** [comment] 2015-07-22 16:25
what size screen are you using? (or if you window is smaller than the screen -- what size is that?)

**Comment by yourhead** [comment] 2015-07-22 16:26
the reason i ask is that Stacks changes its behavior a bit when there is not enough space on the screen.

**Comment by leifottosson** [comment] 2015-07-22 16:29
24" Apple display. RW taking up all screen (but not the useless "full screen app" way). Yesterday I'm sure it started open, now it doesn't. Haven't changed anything.

**Comment by ghost** [comment] 2015-07-22 23:29
not sure if it's related but I've talken to detaching my library and having it on my 2nd monitor nice and wide.
After restarting RW it's back to its docked position.
iMac 27" 2015 with 17" Dell, all latest OS, RW, Stacks beta.

**Comment by leifottosson** [comment] 2015-07-23 10:08
Now it's working as it should and starts open. What I have done is that I have had the library undocked in a separate window for some time and then docked it back again. After restarting RW it's open at launch as it should be.

**Comment by yourhead** [comment] 2015-07-27 19:52
i've spent about an hour trying various ways of opening and closing things and i'm afraid i can't duplicate this bug with a full sized window.

there are some odd behaviors with very small windows when both sidebars don't have room to fit (i think that still needs some work) but with a full sized window it seems very solid to me.

i'm guessing that perhaps i corrected this bug when i was working on some of the width persistence issues.  if you do still see this bug, please let me know. if you can provide some steps for me to reproduce this bug, please do and we'll reopen.

**Closed as completed by yourhead** 2015-07-27 19:52 UTC
Labels: bug
