### ISSUE TITLE
child stack access to %id%

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#83] opened 2015-05-27 03:53 UTC
Had an idea with the new child stack api that is out of the box… my Jack stack has a TON of settings. I thought that it may be interesting to have a main Jack stack and then add child stacks that solely add functionality to the main stack. Example… add a border, shadow, etc.

The idea behind this is to reduce the code that is exported to just the features that the customer wanted (without a ton of stack if statements)

If the child is a wrapperless stack (i.e. no stacks divs) then %id% would simply be the parent. In my use case with Jack, the child stack would not have any html… just CSS or JS

**Comment by yourhead** [comment] 2015-06-11 21:30
i think this is a good idea in general -- but i think we should give it a special template name, overloading %id% for this special case seems confusing

**Comment by yourhead** [comment] 2015-06-11 22:06
closing as duplicate of #146 #147 -- which has a more concise description

**Closed as completed** 2015-06-11 22:07 UTC
Labels: duplicate, enhancement
