### ISSUE TITLE
switch from .stack to .devstack without restart = crash

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#321] opened 2015-07-19 15:43 UTC
If I swap out a `.stack` for a `.devstack` while RapidWeaver is running, this causes a crash. I understand why this happens and its totally my fault but figured that I would let you know...  in case its trappable.

**Comment by yourhead** [comment] 2015-07-19 15:47
please post crash report for crashing bugs

**Comment by joeworkman** [comment] 2015-07-19 21:16
Sorry. I assumed it was easy enough to replicate. I will post a report next time I do this... won't be long. I must have done it 5 times today. :-)

**Comment by yourhead** [comment] 2015-07-19 21:19
when an open bundle goes missing there are any number of things that can go wrong -- so it's quite possible for you to crash in one spot and someone else to crash in a different spot.

so, i might crash, fix that crash, and close this bug -- but the crash you see would be unfixed.

the crash-log helps me make sure that the crash i fix is the one that you had.

**Comment by yourhead** [comment] 2015-07-20 07:14
ok, i've tried this one a few times today. can't make it happen.

i can make some odd things happen if i make that change then do some other really interesting things afterward. but i haven't seen it crash just from changing the file name.

it likely has something to do with some specifics of the situation.  without any more info, i'm kind of dead in the water on this one.

**Comment by yourhead** [comment] 2015-07-21 05:43
i think i may have just bumped into the source of this crash. i was not able to ever reproduce this crash, but i have a hunch that this bad line of code may have been responsible for what you saw. you'll have to let me know if it's gone in beta 8

**Comment by joeworkman** [comment] 2015-07-21 19:11
Actually in b7, it looks like I can switch between a stack and a devstack with no problems. and I don't even need to restart RapidWeaver.

**Comment by yourhead** [comment] 2015-07-21 19:17
LOL

i hadn't done anything to this code before b8 (which you don't have).
"I assumed it was easy enough to replicate"
Apparently not since you can't replicate it yourself.  

:trollface:

that said, this should all be getting bit better in b8

**Closed as completed** 2015-07-21 21:00 UTC
Labels: bug, doesn't repeat
