### ISSUE TITLE
When adding a stacks page, it does not go full screen

### ISSUE THREAD

**Issue by zeebe** [yourhead/s3#673] opened 2017-02-16 20:03 UTC
This does not happen all of the time, but I have noticed it happening since 7.2.x, and I can repeat it in 7.3. Here is how I see it
Open RapidWeaver
Add a stacks page and it looks like this:
![screen shot 2017-02-16 at 1 55 03 pm](https://cloud.githubusercontent.com/assets/1202391/23038522/f25d56f0-f44f-11e6-9070-98b704293248.png)
It continues to stay that way until I open the Inspector, even adding stacks to the page do nothing.
![screen shot 2017-02-16 at 1 58 26 pm](https://cloud.githubusercontent.com/assets/1202391/23038562/176850ee-f450-11e6-8e27-9449e6c4b00a.png)

**Comment by yourhead** [comment] 2017-02-16 21:07
yes, it's in the latest 7.3. i see it too. i'll update soon.

**Comment by yourhead** [comment] 2017-06-15 16:40
does this still happen? i made some changes and no longer seem to be able to duplicate this.

**Comment by joeworkman** [comment] 2017-06-15 17:00
It still happens... 

1. Create a new project. 
2. Add a Stacks page. The inspector opens but is blank. 
3. Add a stack to the page and select it. The settings pane does not appear.

**Comment by yourhead** [comment] 2017-06-15 17:03
Never happens for me.  Maybe there's some setting involved here?

**Comment by yourhead** [comment] 2017-06-15 17:04
I shouldn't say "never" -- it did happen with a RW beta a few months ago. But it was short lived. Now it's back to "normal" which is that the inspector sidebar is always closed when Stacks opens.

**Comment by joeworkman** [comment] 2017-06-15 17:17
Got it... I have "Library Closed on Startup" unchecked.

**Comment by joeworkman** [comment] 2017-06-15 17:17
Once I enable that, this behavior stops

**Comment by yourhead** [comment] 2017-06-15 18:29
Checked or unchecked -- I can't make it do this. Please take a minute or two and answer as many as you can. Thoroughness would be awesome.

OK, let's walk through the basics:

Stacks Version:
RW Version:
macOS Version:

Since this is related to the screen size:
Retina/Non?
Screen Size?
Window Size?
Does changing any of these things vary the behavior (e.g.: if you make the window really big or really small does the issue get better/worse)

Stack Prefs:
Just post a screenshot of what you have in the General tab please.
Does changing any of these prefs change the behavior? Does the behavior come back if you change the setting back?

RW Prefs:
Same for General prefs of in RW.

Steps:
1. Launch RW
2. New Project
3. New Stacks page
Any other steps?
Are any of these steps wrong?
If you do different things (like open an existing file) does it change the behavior?

**Comment by yourhead** [comment] 2017-06-16 14:58
Any more info?  Thx

**Comment by joeworkman** [comment] 2017-06-16 16:51
RapidWeaver Version 7.5 (18719b)
Stacks 3.3.0b11 (there is no way to find the Stacks version from inside Stacks?)
MacOS 10.12.5 (16F73)

Happens on both Retina and Non-Retina Macs. 
15" retina and 27" Cinema display
Windows size: 1500x1000 (does not seem to matter though)
Resizing the window while it was in this condition fixes it. Crazy enough, it won't even do it anymore now! Now the behavior is as you would expect. 

However, with the latest beta build, this looked a little different. Instead of the blank space being the same size as the page inspector, its smaller now. 
![screen shot 2017-06-16 at 9 23 10 am](https://user-images.githubusercontent.com/225628/27236311-5f9828c6-5279-11e7-80ce-7d56e92221df.jpg)

**Comment by yourhead** [comment] 2017-06-17 17:11
"Crazy enough, it won't even do it anymore now!"

So can you make this happen? Or did it become "cured"?


Two experiments to try:

1.  Can you repeat the behavior if you create a different type of page (not a stacks page, but a styled text page or whatever)? Or is this problem isolated to Stacks?


2. It would be great to see the contents of your prefs file right when the problem is happening. This is non-trivial to get from a customer -- but for you...   😃 

Right after seeing the problem -- without moving the window or changing anything at all -- switch to Terminal and type:

defaults read com.realmacsoftware.rapidweaver > ~/Desktop/rw_prefs

Then send me that dumpfile.  I can use it to emulate your prefs and hopefully duplicate the bug.

**Comment by yourhead** [comment] 2017-06-23 18:51
closing unless some new info arises. i still have never seen this bug to date. i have no idea how to duplicate it. under what circumstances it might appear. what preferences are needed to trigger it. 

i'll re-open if new info arrises. or if i bump into something in the code that seems like a potential culprit.

**Closed as completed** 2017-06-23 18:51 UTC
Labels: bug, doesn't repeat
